SimpleNews/Components/NavMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SimpleNews.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleNews.Components
{
    public class NavMenuViewComponent:ViewComponent
    {
        INewsRepository repository;
        public NavMenuViewComponent(INewsRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
            => View(repository.GetNews().Select(x => x.Tags).Distinct().OrderBy(x => x));
    }
}

SimpleNews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <title>@ViewData["Title"] - SimpleNews</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col col-sm-9 navbar-brand h1 pt-5"><h1>Simple News</h1></div>
            <div class="col bottom-right align-items-center pt-1">
                <form method="post">
                    <div class="col-sm-10">
                        <div class="form-group row">
                            <label for="Login"></label>
                            <input type="email" class="form-control" value="login" />
                        </div>

                        <div class="form-group row">
                            <label for="Password"></label>
                            <input type="password" class="form-control" value="password" />
                        </div>

                    </div>
                    <button type="submit" class="btn btn-primary">Войти</button>
                    <button type="button" class="btn btn-primary ml-2">Регистрация</button>

                </form>

            </div>
        </div>

        <div class="row mt-3">
            <div> @await Component.InvokeAsync("NavMenu") </div>
            @RenderBody()
        </div>

    </div>

</body>
</html>